name: Chrome Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set tag
              id: tag
              run: echo "manifest=$(jq -c . < manifest.json)" >> $GITHUB_ENV

            - name: Create zip
              run: make build/chrome

            - name: Upload to Chrome Web Store
              uses: wdzeng/chrome-extension@b167f5b883d2ade3c4209eccb62fa8307ae44434
              with:
                extension-id: onilpcgmnpikffebghpncnnapebndpaj
                zip-path: build/chrome/dblpSearch-ext-${{ fromJson(env.manifest).version }}.zip
                client-id: ${{ secrets.CHROME_CLIENT_ID }}
                client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
                refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
                upload-only: false