name: Chrome Release

on:
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set tag
              id: tag
              run: echo "manifest=$(jq -c . < manifest.firefox.json)" >> $GITHUB_ENV

            - name: Create zip
              run: make chrome

            - name: Upload to Chrome Web Store
              uses: wdzeng/chrome-extension@v1
              with:
                extension-id: onilpcgmnpikffebghpncnnapebndpaj
                zip-path: dist/chrome/dblpSearch-ext-${{ fromJson(env.manifest).version }}.zip
                client-id: ${{ secrets.CLIENT }}
                client-secret: ${{ secrets.SECRET }}
                refresh-token: ${{ secrets.REFRESH_TOKEN }}
                upload-only: true