name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create zip file
              run: zip -r release.zip .

            - name: Set tag
              id: tag
              run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

            - name: Create a Release
              uses: elgohr/Github-Release-Action@v5
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                title: dblp Search ${{ steps.tag.outputs.version }}

            - name: Create zip
              run: make build/chrome
              
            - name: Upload to Chrome Web Store
              uses: wdzeng/chrome-extension@v1
              with:
                extension-id: onilpcgmnpikffebghpncnnapebndpaj
                zip-path: dist/chrome/dblpSearch-ext-${{ fromJson(env.manifest).version }}.zip
                client-id: ${{ secrets.CHROME_CLIENT_ID }}
                client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
                refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
                upload-only: false  # Optional, default is false, menas upload and publish

            - name: Create xpi
              run: make build/firefox

            - name: Upload to the Firefox Add-ons Store
              uses: wdzeng/firefox-addon@v1
              with:
                addon-guid: dblpSearch@fcalefato.dev
                xpi-path: dist/firefox/dblpSearch-addon-${{ steps.tag.outputs.version }}.xpi
                self-hosted: false
                license: MIT
                jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
                jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}

            - name: Upload to the Edge Add-ons Store
              uses: wdzeng/edge-addon@v1
              with:
                product-id: mgiijnhdenbgibgdffibiigpmnkgmboc
                zip-path: dist/chrome/dblpSearch-ext-${{ steps.tag.outputs.version }}.zip
                client-id: ${{ secrets.EDGE_CLIENT_ID }}
                client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
                access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}