name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create zip file
              run: zip -r release.zip .

            - name: Set tag
              id: tag
              run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

            - name: Set version
              id: version
              run: echo "manifest=$(jq -c . < manifest.json)" >> $GITHUB_ENV

            - name: Create a Release
              uses: elgohr/Github-Release-Action@v5
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                title: dblp Search ${{ steps.tag.outputs.version }}

            - name: Create zip
              run: make build/chrome
              
            - name: Upload to Chrome Web Store
              uses: wdzeng/chrome-extension@v1
              with:
                extension-id: onilpcgmnpikffebghpncnnapebndpaj
                zip-path: build/chrome/dblpSearch-ext-${{ fromJson(env.manifest).version }}.zip
                client-id: ${{ secrets.CHROME_CLIENT_ID }}
                client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
                refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
                upload-only: false

            - name: Create xpi
              run: make build/firefox

            - name: Upload to the Firefox Add-ons Store
              uses: wdzeng/firefox-addon@v1
              with:
                addon-guid: dblpSearch@fcalefato.dev
                xpi-path: build/firefox/dblpSearch-addon-${{ fromJson(env.manifest).version }}.xpi
                self-hosted: false
                license: MIT
                jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
                jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}

            - name: Upload to the Edge Add-ons Store
              uses: wdzeng/edge-addon@v1
              with:
                product-id: ${{ secrets.EDGE_PRODUCT_ID }}
                zip-path: build/chrome/dblpSearch-ext-${{ fromJson(env.manifest).version }}.zip
                client-id: ${{ secrets.EDGE_CLIENT_ID }}
                client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
                access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
